### PR TITLE
GSoC Replace payload port

### PR DESCRIPTION
**Pull request by RoyDePoy**
Added Replace payload, parser, serializer and tests

### CODE REVIEW

**Comment by Kev** [comment]
Thanks for this. The port looks good, I've just a couple of quibbles that I've commented on above.

**Comment by Kev** [comment]
This has just run through the CI system, and the unit tests seem to fail; are they passing for you?

**Comment by RoyDePoy** [comment]
Oh, you're right. Funny thing, none of the tests are passing.

**Comment by RoyDePoy** [comment]
Ok, I didn't have hamcrest correctly configured.
Indeed tests failed. I repaired the Serializer, I'm looking at the Parser.

**Comment by RoyDePoy** [comment]
I identified the mistake.
As I didn't add ReplaceParser to the FullPayloadParserFactoryCollection, during test a RawXMLParser was instanciated instead. Then the returned payload was never a Replace and could never be cast to Replace.
If I'm not wrong again, it now works

**Comment by Kev** [comment]
Thanks. Could you squash these into a single commit with 
Change-Id: If3dc7c0aba6c5817ebff8f53397758d2c37d0cd7
make the first line of the commit message a command (e.g. 'Port Replace payload from Swiften' or 'Add Replace payload', add a Test-Information: detailing what testing you did, and include the BSD message, please. Then I'll feet it into our review/CI system again. For an example, see https://github.com/swift/swift/commit/fedd8d88befb0fa19a58a78a163c200889b5272c

**Comment by Kev** [comment]
I see you've updated the branch, but haven't commented - is this ready for review again?

**Comment by RoyDePoy** [comment]
I had a bit of a battle with Git to include only my work (I still have to learn about Git but this have already been full of lessons).
It is now ready.

**Comment by Kev** [comment]
Thanks, it passed the CI tests this time. I've made some comments in our review system at https://git.swift.im/review/#/c/808/

(Probably easiest if when it presents you with a popup saying about a new format you click the 'revert' button, as there are currently some issues with the new version of Gerrit we deployed).

**Comment by RoyDePoy** [comment]
Fixes following your comments

**Comment by Kev** [comment]
Thanks. I've left another couple of comments.

**Comment by RoyDePoy** [comment]
CapsInfoSerialzer : I must've commit -a, forgetting I hadn't fetched upstream.
ReplaceParserTest : Did not see, I usually agree about not mixing tabs and space. Think I copy-pasted block without seeing it was space indented.

**Comment by Kev** [comment]
Thanks for the update. I've left a couple of comments on https://git.swift.im/review/#/c/808/

**Comment by RoyDePoy** [comment]
Fixes following your comments.

**Pull request closed without merging**
